import { ArrowDown, ArrowRight, BookOpen, Compass, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'

const startingPoints = [
  { icon: Compass, title: "I'm new to AI", text: 'Start from the very beginning and understand what artificial intelligence actually is.', tone: 'bg-mist' },
  { icon: Sparkles, title: 'I already use AI', text: 'Learn how to communicate with AI and get better results from the tools you already use.', tone: 'bg-sand' },
  { icon: BookOpen, title: 'I want to build with AI', text: 'Learn how modern AI applications work and how developers build them.', tone: 'bg-white' },
]

export function HomePage() {
  return <>
    <section className="overflow-hidden border-b border-line bg-cream"><div className="shell grid items-center gap-14 py-16 md:grid-cols-[1fr_0.9fr] md:py-24">
      <div><p className="eyebrow">A calmer way to learn AI</p><h1 className="mt-5 max-w-xl font-display text-5xl font-bold leading-[1.04] tracking-tight text-teal sm:text-7xl">AI doesn't have to be complicated.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted">Learn artificial intelligence from the basics to building real AI applications.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/learn" className="button button-primary">Start learning <ArrowRight size={17} className="ml-2" /></Link><Link to="/learn" className="button button-secondary">Explore curriculum</Link></div><p className="mt-5 text-sm font-bold text-teal">Free forever <span className="mx-2 text-gold">•</span> No account required</p></div>
      <div className="relative mx-auto w-full max-w-md"><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-gold/25" /><div className="relative rounded-[2rem] border border-teal/10 bg-white p-5 shadow-soft sm:p-7"><div className="flex items-center justify-between"><span className="eyebrow">A simple mental model</span><span className="rounded-full bg-sand px-3 py-1 text-xs font-bold text-teal">01</span></div><div className="mt-7 space-y-3"><div className="rounded-2xl bg-cream px-5 py-4 font-bold text-teal">Your words <ArrowDown className="my-2 text-gold" size={18} /><span className="text-sm font-medium text-muted">I want to learn about AI</span></div><div className="flex items-center gap-3"><div className="h-px flex-1 bg-line" /><span className="rounded-full bg-mist px-3 py-2 text-xs font-bold text-teal">tokens</span><div className="h-px flex-1 bg-line" /></div><div className="rounded-2xl bg-teal px-5 py-4 font-bold text-white">AI model <ArrowDown className="my-2 text-gold" size={18} /><span className="text-sm font-medium text-white/70">finds useful patterns</span></div><div className="rounded-2xl border border-gold/30 bg-sand px-5 py-4 font-bold text-teal">A helpful response</div></div></div></div>
    </div></section>
    <section className="shell py-20"><div className="max-w-xl"><p className="eyebrow">Your starting point</p><h2 className="section-title mt-3">Where should I start?</h2><p className="mt-4 text-lg leading-8 text-muted">Not sure where to begin? That's okay. Pick the path that sounds most like you.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{startingPoints.map(({ icon: Icon, title, text, tone }) => <div key={title} className={`rounded-[1.75rem] border border-line p-7 ${tone}`}><Icon className="text-teal" size={25} /><h3 className="mt-12 font-display text-2xl font-bold text-teal">{title}</h3><p className="mt-3 min-h-20 leading-7 text-muted">{text}</p><Link to="/learn" className="mt-5 inline-flex items-center font-bold text-teal">Start here <ArrowRight size={16} className="ml-2" /></Link></div>)}</div></section>
    <section className="bg-white"><div className="shell flex flex-col items-start justify-between gap-6 py-14 sm:flex-row sm:items-center"><div><p className="eyebrow">Learn at your own pace</p><h2 className="mt-2 font-display text-3xl font-bold text-teal">Small ideas become useful skills.</h2></div><Link to="/playground" className="button button-secondary">Try a playground <ArrowRight size={17} className="ml-2" /></Link></div></section>
  </>
}
