import { ArrowRight, BookOpen, Compass, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'

const startingPoints = [
  { icon: Compass, title: "I'm starting fresh", text: 'Build the mental models, math, Python, and software habits that make AI easier to understand.', tone: 'bg-mist', to: '/learn?stage=foundation' },
  { icon: BookOpen, title: 'I want to become a Python developer', text: 'Learn maintainable Python, testing, APIs, algorithms, package design, and project practice.', tone: 'bg-white', to: '/dashboard?section=plan&goal=python-developer' },
  { icon: Sparkles, title: 'I already use AI', text: 'Move from prompts to structured outputs, evaluation, agents, and reliable production systems.', tone: 'bg-sand', to: '/learn?stage=ai-engineering' },
  { icon: Compass, title: 'I like math and research', text: 'Study modeling, optimization, inference, numerical methods, and reproducible AI experiments.', tone: 'bg-white', to: '/dashboard?section=plan&goal=ai-mathematics' },
  { icon: BookOpen, title: 'I want to lead technical work', text: 'Practice customer discovery, scope, communication, planning, negotiation, and leadership.', tone: 'bg-sand', to: '/dashboard?section=plan&goal=technical-leadership' },
]

export function HomePage() {
  return <>
    <section className="overflow-hidden border-b border-line bg-cream"><div className="shell grid items-center gap-14 py-16 md:grid-cols-[1fr_0.9fr] md:py-24">
      <div><p className="eyebrow">A clearer path into AI.</p><h1 className="mt-5 max-w-xl font-display text-5xl font-bold leading-[1.04] tracking-tight text-teal sm:text-7xl">Understand how AI works. Build with confidence.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-muted">Follow a practical path from AI fundamentals to software engineering, cloud, and architecture.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/learn" className="button button-primary">See the career path <ArrowRight size={17} className="ml-2" /></Link><Link to="/learn?stage=foundation" className="button button-secondary">Start at foundation</Link></div><p className="mt-5 text-sm font-bold text-teal">Free forever</p></div>
      <div className="relative mx-auto w-full max-w-md"><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-gold/25" /><div className="relative rounded-[2rem] border border-teal/10 bg-white p-5 shadow-soft sm:p-7"><div className="flex items-center justify-between"><span className="eyebrow">A simple mental model</span><span className="rounded-full bg-sand px-3 py-1 text-xs font-bold text-teal">01 / 03</span></div><div className="mt-7 space-y-3"><div className="flex items-start gap-3 rounded-2xl bg-cream p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white text-xs font-bold text-teal">01</span><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-muted">Input</p><p className="mt-2 font-display text-xl font-bold text-teal">Your words</p><p className="mt-1 text-sm leading-6 text-ink">I want to learn about AI</p></div></div><div className="flex items-center gap-3 px-4"><div className="h-7 border-l-2 border-dashed border-gold" /><span className="rounded-full bg-mist px-3 py-2 text-xs font-bold text-teal">tokens</span><span className="text-xs font-bold uppercase tracking-widest text-muted">break into pieces</span></div><div className="flex items-start gap-3 rounded-2xl bg-teal p-4 text-white"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white/15 text-xs font-bold text-white">02</span><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-white/60">Process</p><p className="mt-2 font-display text-xl font-bold">AI model</p><p className="mt-1 text-sm leading-6 text-white/70">finds useful patterns</p></div></div><div className="flex items-center gap-3 px-4"><div className="h-7 border-l-2 border-dashed border-gold" /><span className="text-xs font-bold uppercase tracking-widest text-muted">generate</span></div><div className="flex items-start gap-3 rounded-2xl border border-gold/30 bg-sand p-4"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white text-xs font-bold text-teal">03</span><div><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-ink">Output</p><p className="mt-2 font-display text-xl font-bold text-teal">A helpful response</p><p className="mt-1 text-sm leading-6 text-ink">shaped by context and probability</p></div></div></div></div></div>
    </div></section>
    <section className="shell py-20"><div className="max-w-2xl"><p className="eyebrow">Your starting point</p><h2 className="section-title mt-3">Where should I start?</h2><p className="mt-4 text-lg leading-8 text-muted">This is your onboarding. Choose the route that sounds most like your goal, then follow the next recommended step instead of trying to learn everything at once.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{startingPoints.map(({ icon: Icon, title, text, tone, to }) => <div key={title} className={`rounded-[1.75rem] border border-line p-6 ${tone}`}><Icon className="text-teal" size={25} /><h3 className="mt-8 font-display text-2xl font-bold text-teal">{title}</h3><p className="mt-3 min-h-24 leading-7 text-ink">{text}</p><Link to={to} className="mt-5 inline-flex items-center font-bold text-teal">Start here <ArrowRight size={16} className="ml-2" /></Link></div>)}</div><div className="mt-8 grid gap-3 border-t border-line pt-8 sm:grid-cols-3"><div><span className="text-xs font-bold uppercase tracking-widest text-[#8b5e2f]">01</span><p className="mt-2 font-bold text-teal">Choose a route</p><p className="mt-1 text-sm leading-6 text-muted">Start from your goal, not from a random lesson.</p></div><div><span className="text-xs font-bold uppercase tracking-widest text-[#8b5e2f]">02</span><p className="mt-2 font-bold text-teal">Follow the next step</p><p className="mt-1 text-sm leading-6 text-muted">Use the plan and progress markers to keep moving.</p></div><div><span className="text-xs font-bold uppercase tracking-widest text-[#8b5e2f]">03</span><p className="mt-2 font-bold text-teal">Build proof</p><p className="mt-1 text-sm leading-6 text-muted">Turn lessons into projects and portfolio evidence.</p></div></div></section>
    <section className="bg-white"><div className="shell flex flex-col items-start justify-between gap-6 py-14 sm:flex-row sm:items-center"><div><p className="eyebrow">Learn at your own pace</p><h2 className="mt-2 font-display text-3xl font-bold text-teal">Small ideas become useful skills.</h2></div><Link to="/playground" className="button button-secondary">Try a playground <ArrowRight size={17} className="ml-2" /></Link></div></section>
  </>
}
