import { LegalPage } from './LegalPage'

export function PrivacyPage() {
  return <LegalPage
    eyebrow="Privacy policy"
    title="Your learning data, explained plainly."
    intro="This Privacy Policy explains how Tinted Technologies handles information when you use Tinted Learning, its free AI education service."
    sections={[
      { title: '1. Information we collect', paragraphs: ['If you browse without signing in, Tinted Learning is designed to provide lessons and practice experiences without asking for an account. If you create or use an account, we may receive account information such as your name, email address, profile image, authentication provider, and a provider-specific account identifier. Profile images are uploaded through Clerk. We do not ask for sensitive personal information to use the learning service.', 'We collect learning activity that is needed for the service, including completed lesson IDs and derived progress such as your current stage, module, and lesson. Text, prompts, slider values, Python code, and Python output entered into the interactive playgrounds are processed in your browser and are not sent to Tinted Technologies by the application. They are held in page memory and are normally cleared when you reload or leave the page. Please do not enter passwords, API keys, confidential business information, or sensitive personal data into practice tools.'] },
      { title: '2. Clerk authentication and Google Sign-In', paragraphs: ['Tinted Learning uses Clerk to provide authentication, account management, session security, and account deletion controls. Clerk may set cookies or use browser storage to maintain your sign-in session and protect the service. When you choose Google Sign-In, Google shares the account information needed to authenticate you, and Google processes data under Google’s own privacy policy. Tinted Technologies does not receive your Google password.', 'Clerk and Google are independent third-party providers. Their handling of information, including their retention and international transfers, is governed by their own notices and terms.'] },
      { title: '3. How we use information', paragraphs: ['Tinted Technologies uses information to provide and secure Tinted Learning, authenticate users, save and restore learning progress, manage profile images, respond to requests, diagnose technical problems, and prevent abuse. We do not sell your personal information. We do not use your account data to make decisions about your eligibility for employment, credit, housing, education, or other services.'] },
      { title: '4. Cookies and local storage', paragraphs: ['Clerk may use essential cookies and similar technologies to keep you signed in, maintain session security, and remember authentication state. These technologies are necessary for account features to work. Learning progress for signed-in users is stored in Clerk account metadata, not only in your browser, so it can persist across devices.', 'The Tinted Learning application does not intentionally write to localStorage or sessionStorage and does not currently use advertising cookies, analytics cookies, or behavioral tracking. Your browser may still retain cache or cookies set by Clerk, linked services, or third-party content you open. Removing essential authentication cookies may sign you out or disable account features.'] },
      { title: '5. Third-party services and links', paragraphs: ['The application uses Clerk for authentication, account management, session security, progress metadata, and profile-image uploads. Google is an optional sign-in provider. The site loads its fonts from Google Fonts and loads the browser-based Python runtime from jsDelivr (the Pyodide project) when you open the Python playground. Those services may receive your IP address and standard request information when your browser requests their files or authentication services, subject to their own policies.', 'Tinted Learning also links to resources from organizations such as Google, OpenAI, GitHub, Microsoft, AWS, and others. Opening an external link takes you to a separate service with its own privacy practices. Tinted Technologies does not control those services or the information they collect.'] },
      { title: '6. Retention, security, and deletion', paragraphs: ['We retain account and progress information for as long as needed to provide the service, comply with legal obligations, resolve disputes, enforce agreements, and protect the service. We use reasonable administrative and technical safeguards, but no online service can guarantee absolute security.', 'You can clear learning progress from the dashboard and request deletion of your account. Account deletion removes or initiates removal of information associated with your Tinted Learning account, subject to information that a provider or Tinted Technologies must retain for legal, security, or operational reasons.'] },
      { title: '7. Your choices and contact', paragraphs: ['You can choose not to create an account, decline Google Sign-In, sign out, clear progress, or request account deletion. You may contact Tinted Technologies with privacy questions or requests through the contact method published on the Tinted Learning website. We may need to verify a request before acting on it.', 'Tinted Technologies may revise this policy as the service changes. The current version and effective date will always appear on this page.'] },
    ]}
  />
}