import { LegalPage } from './LegalPage'

export function TermsPage() {
  return <LegalPage
    eyebrow="Terms of use"
    title="A clear agreement for learning in public."
    intro="These Terms of Use govern your access to Tinted Learning, a free AI education service from Tinted Technologies. By using Tinted Learning, you agree to these terms."
    sections={[
      { title: '1. The service', paragraphs: ['Tinted Learning provides educational lessons, explanations, browser-based practice tools, project guidance, and related resources. The service is provided for learning and experimentation. It is not professional, legal, financial, medical, employment, or security advice, and completing a lesson does not guarantee a job, certification, or particular result.', 'Some resources link to third-party websites, documentation, or services. Those destinations have their own terms and policies. Tinted Technologies does not control or endorse every third-party resource and is not responsible for its availability, content, or practices.'] },
      { title: '2. Accounts and Google Sign-In', paragraphs: ['You may browse much of Tinted Learning without an account. Features such as saved learning progress require you to sign in. Authentication is provided by Clerk. You may sign in using Google Sign-In or another method Clerk makes available. When you use Google Sign-In, Google and Clerk process information under their own terms and privacy policies.', 'You are responsible for keeping your account access secure and for activity under your account. You must provide information that you are permitted to provide and must not impersonate another person or use the service to access another person’s account.'] },
      { title: '3. Learning progress and account controls', paragraphs: ['When you are signed in, Tinted Learning may save completed lesson IDs and calculated curriculum details to your Clerk account so that your progress can follow you between sessions. You can clear saved progress from the account dashboard. You can also request account deletion through the available account controls or by contacting Tinted Technologies. Deleting an account may not immediately remove information retained by Clerk or another provider where retention is required by law or needed for security and fraud prevention.', 'You keep ownership of text, prompts, and code you enter into a practice tool. The interactive playgrounds process that material in your browser and the application does not send it to Tinted Technologies. The Python playground downloads the Pyodide runtime from jsDelivr. Do not submit confidential, sensitive, or personal information to exercises or code playgrounds.'] },
      { title: '4. Acceptable use', paragraphs: ['You may use Tinted Learning only in a lawful way and in a way that does not disrupt the service or harm other people. Do not probe, scrape, overload, reverse engineer, bypass authentication, upload malicious code, infringe rights, or use the service to create or distribute harmful content. Tinted Technologies may limit or suspend access when reasonably necessary to protect the service, users, or others.'] },
      { title: '5. Intellectual property', paragraphs: ['Tinted Learning’s original software, curriculum, text, visual design, and branding belong to Tinted Technologies or its licensors. These Terms give you a limited, personal, non-exclusive right to access and use the service for its intended educational purpose. Tinted Learning does not grant permission to reproduce, resell, or redistribute its original materials as a competing course or service.'] },
      { title: '6. Availability and disclaimers', paragraphs: ['Tinted Learning is offered on an “as is” and “as available” basis. Tinted Technologies does not promise that the service will always be available, error-free, secure, or suitable for every purpose. Lessons and external resources can become outdated, so verify important information independently before acting on it.', 'To the extent permitted by law, Tinted Technologies is not liable for indirect, incidental, special, consequential, or lost-profit damages arising from your use of the service. Nothing in these Terms limits rights or liabilities that cannot legally be limited.'] },
      { title: '7. Changes and contact', paragraphs: ['Tinted Technologies may update these Terms when the service or law changes. The updated version will be posted here with a new effective date. Continued use after an update means you accept the revised Terms.', 'Questions about these Terms can be sent to Tinted Technologies through the contact method published on the Tinted Learning website.'] },
    ]}
  />
}